/**
 * Generates an email template for data deletion requests (CCPA / GDPR / state privacy laws).
 * Pure client-side — no data leaves the browser except via the user's own email client.
 */
export const generateEmailTemplate = (broker, userData) => {
  const [id, name, cat, diff, url, method, data, time, email, types, status] = broker;
  const { fullName, email: userEmail, phone, address, city, state } = userData;

  const subject = `Data Deletion Request Under CCPA/GDPR - ${fullName || '[Your Name]'}`;
  
  const body = `To whom it may concern at ${name},

My name is ${fullName || '[Your Full Name]'} and I am writing to formally request the permanent deletion of any and all personal information you have collected, processed, or stored about me.

This request is made pursuant to applicable privacy laws (CCPA, CPRA, VCDPA, GDPR, and similar state/regional regulations).

My identifying information for cross-reference is:
- Full Name: ${fullName || '[Your Full Name]'}
- Primary Email: ${userEmail || '[your@email.com]'}
${phone ? `- Phone Number: ${phone}` : ''}
${city || state ? `- Location: ${city || ''}${city && state ? ', ' : ''}${state || ''}` : ''}
${address ? `- Physical Address: ${address}` : ''}

I request that you:
1. Delete all personal data you hold about me from your systems and backups.
2. Direct any service providers, partners, or data processors who received my data to also delete it.
3. Confirm in writing (email is acceptable) once the deletion is complete.

Please respond within the legally required timeframe (typically 45 days or less).

Best regards,
${fullName || '[Your Full Name]'}
${userEmail || ''}

---
Generated by Antigravity Data Broker Removal Agent
Privacy-first tool • All processing happens locally in your browser`;

  let recipient = email;
  if (!recipient) {
    try {
      const hostname = new URL(url).hostname.replace(/^www\./, '');
      recipient = `privacy@${hostname}`;
    } catch (e) {
      recipient = 'privacy@data-broker.com';
    }
  }

  return {
    to: recipient,
    subject,
    body,
    mailto: `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
  };
};

/**
 * Reliable "Gmail Protocol" action.
 * Copies the full professional email to clipboard and opens the user's mail client via mailto:.
 * This is the only reliable cross-platform method without requiring OAuth / backend.
 * 
 * For power users who want true one-click drafts in Gmail:
 *   - Use the "External Transfer" button (opens mailto)
 *   - Or paste the copied text into Gmail web/app manually (very fast)
 */
export async function createGmailDraft(to, subject, body) {
  try {
    // 1. Copy full professional email to clipboard — safest & most reliable cross-platform method
    const fullEmail = `To: ${to}\nSubject: ${subject}\n\n${body}`;
    await navigator.clipboard.writeText(fullEmail);

    // 2. Do NOT auto-navigate with window.location.href — it destroys the SPA session and progress.
    //    User can use the "External Transfer" link in the Draft modal (proper <a href="mailto:...">)
    //    or paste the copied content into Gmail / their mail client manually.
    return { 
      ok: true, 
      message: "Professional email copied to clipboard. Use 'External Transfer' or paste into Gmail." 
    };
  } catch (error) {
    console.error('Clipboard failed:', error);
    return { 
      ok: false, 
      message: "Could not copy to clipboard. Select and copy the text from the preview panel manually." 
    };
  }
}

/**
 * Pure clipboard copy helper (used by the copy button in the modal)
 */
export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
